name: Temporary Windows RDP (Playit)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable RDP
        run: |
          net user runneradmin Test@12345
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Download Playit
        run: |
          $url = "https://playit.gg/download/windows"
          Invoke-WebRequest -Uri $url -OutFile "playit.exe"

      - name: Start Playit
        run: |
          .\playit.exe

      - name: Keep Runner Alive
        run: Start-Sleep -Seconds 21600
